### PR TITLE
Crystal 0.19.x compatibility

### PR DESCRIPTION
**Pull request by feifanzhou**

### CODE REVIEW

**Comment by dukex** [comment]
Duplicated with #55

**Comment by waterlink** [comment]
Both #55 and #56 are pretty much the same. I will take one of them and will make it work with latest crystal release.

**Comment by waterlink** [comment]
> Both #55 and #56 are pretty much the same. I will take one of them and will make it work with latest crystal release.

cc @feifanzhou @dukex and @sdogruyol

**Comment by sdogruyol** [comment]
@waterlink if you want you can pick #55 👍

**Comment by waterlink** [comment]
Done and released new version: `1.0.2`

**Pull request closed without merging**
