### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sdogruyol**

### CODE REVIEW

**Comment by waterlink** [comment]
Merged manually after fixing test suite. (there was problem with `mocks` dependency, needed to update its usage).

**Comment by waterlink** [comment]
Thanks!

**Comment by sdogruyol** [comment]
Hey thanks. Great work on this are you gonna add postgres driver soon?

**Comment by waterlink** [comment]
Yep, it is on my TODO list. Though I am a bit busy at my job lately..

**Pull request merged**
