### PR TITLE
Upgrade to crystal 0.20.x

### LINKED ISSUE #58: Compiler error
Hi,
I just wanted to try this ActiveRecord implementation, but I get the following compiler error when I require it:

```
in ./libs/active_record/active_record.cr:1: while requiring "./registry"

require "./registry"
^

in ./libs/active_record/registry.cr:1: while requiring "./adapter"

require "./adapter"
^

in ./libs/active_record/adapter.cr:1: while requiring "./types"

require "./types"
^

in ./libs/active_record/types.cr:98: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.     
   2. 
   3.     struct Int
   4.       def not_null! : Int
   5.         self as Int
   6.       end
   7. 
   8.       def null?
   9.         false
  10.       end
  11. 
  12.       struct Null
  13.         def not_null! : NoReturn
  14.           ::raise ActiveRecord::NullCheckFailed.new("It is Int::Null")
  15.         end
  16. 
  17.         def inspect
  18.           "Null(#{"struct"})"
  19.         end
  20. 
  21.         def null?
  22.           true
  23.         end
  24.       end
  25.     end
  26.   
--------------------------------------------------------------------------------
Syntax error in expanded macro: register_type:5: unexpected token: as

        self as Int
             ^

================================================================================

ActiveRecord.register_type(:struct, Int, Int, register: false)
```

These are the versions I use:

```
Crystal 0.19.2 [d81c32c] (2016-09-16)
Using active_record (1.0.1)
Using pool (0.2.3)
Using query (0.1.2)
Using sqlite_adapter (0.1.0)
Using sqlite3 (0.6.0)
Using db (ae6a68f00e964df3ae6fbd3e53c986d613ced5c2)
```

### PR DESCRIPTION
**Pull request by waterlink**
closes #58 
closes #55 
closes #56

### CODE REVIEW

**Comment by sdogruyol** [comment]
@waterlink good job 👍 Are you going to maintain `active_record.cr` from now on?

**Comment by waterlink** [comment]
Yes. Help is welcome, of course ;)

**Comment by sdogruyol** [comment]
@waterlink that's great to hear 🎉

**Comment by waterlink** [comment]
Also, I'm still fixing MySQL adapter right now.

**Comment by sdogruyol** [comment]
@waterlink have you ever thought of migration to `crystal-db`?

**Comment by waterlink** [comment]
Yes. That would be nice.

I am fighting with the adapter though. Mostly crystal's generics giving me
headache right now. Changing to crystal-db wouldn't fix the generics
problem.. :(

**Comment by waterlink** [comment]
Just released fixed version of `mysql_adapter` (v0.5.1). Because generics + inheritance is still broken, had to do some string-typing kind of polymorphism.

**Comment by waterlink** [comment]
Now will check postgres and sqlite adapters

**Pull request merged**
